# Example configuration - replace with your actual values or use environment variables
# endpoint: ${PLATFORMURL:-http://localhost:8080}
# auth:
#   client_id: ${CLIENTID:-opentdf-client}
#   client_secret: ${CLIENTSECRET}

endpoint: http://localhost:8080
auth:
  client_id: opentdf-client
  client_secret: secret