name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DERIVED_DATA_PATH: ".build"
  SWIFT_CACHE_KEY: "swift-v6-${{ github.ref }}"

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache Homebrew dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /usr/local/Homebrew
          key: ${{ runner.os }}-brew
          restore-keys: |
            ${{ runner.os }}-brew-
            
      - name: Install SwiftFormat & SwiftLint
        run: |
          brew install swiftformat swiftlint || true
          
      - name: Run SwiftFormat
        run: swiftformat --swiftversion 6.0 . --lint
        
      - name: Run SwiftLint
        run: swiftlint --strict

  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ env.SWIFT_CACHE_KEY }}
          restore-keys: |
            swift-v6-
            
      - name: Build Debug
        run: swift build -v
        
      - name: Build Release
        run: swift build -c release -v
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ env.DERIVED_DATA_PATH }}/**/debug/OpenTDFKit
            ${{ env.DERIVED_DATA_PATH }}/**/release/OpenTDFKit
          retention-days: 7

  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ env.SWIFT_CACHE_KEY }}
          restore-keys: |
            swift-v6-
            
      - name: Run tests
        run: swift test -v

  benchmark:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ env.SWIFT_CACHE_KEY }}
          restore-keys: |
            swift-v6-
            
      - name: Run KeyStore Benchmarks
        run: swift test --configuration release --filter KeyStoreBenchmarkTests | tee keystore-benchmark.log
        
      - name: Run KASService Benchmarks
        run: swift test --configuration release --filter KASServiceBenchmarkTests | tee kasservice-benchmark.log
        
      - name: Run NanoTDF Benchmarks
        run: swift test --configuration release --filter NanoTDFBenchmarkTests | tee nanotdf-benchmark.log
        
      - name: Upload benchmark logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            *-benchmark.log
          retention-days: 7
