name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DERIVED_DATA_PATH: ".build"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Swift 6.2
        run: |
          # Remove any existing Swift installation
          sudo rm -rf /usr/bin/swift /usr/bin/swiftc

          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y binutils git gnupg2 libc6-dev libcurl4-openssl-dev libedit2 libgcc-9-dev libpython3.8 libsqlite3-0 libstdc++-9-dev libxml2-dev libz3-dev pkg-config tzdata unzip zlib1g-dev curl

          # Download and install Swift 6.2
          wget https://download.swift.org/swift-6.2-release/ubuntu2204/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-6.2-RELEASE-ubuntu22.04.tar.gz
          sudo mv swift-6.2-RELEASE-ubuntu22.04 /usr/share/swift

          # Create symlinks for system-wide access
          sudo ln -sf /usr/share/swift/usr/bin/swift /usr/bin/swift
          sudo ln -sf /usr/share/swift/usr/bin/swiftc /usr/bin/swiftc
          sudo ln -sf /usr/share/swift/usr/bin/swift-build /usr/bin/swift-build
          sudo ln -sf /usr/share/swift/usr/bin/swift-package /usr/bin/swift-package
          sudo ln -sf /usr/share/swift/usr/bin/swift-test /usr/bin/swift-test

          # Add to PATH for this step and future steps
          echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH
        
      - name: Verify Swift 6.2 installation
        run: |
          swift --version
          which swift
          swift --version | grep -q "6.2" || (echo "Error: Swift 6.2 not properly installed" && exit 1)
          
      - name: Cache SwiftFormat
        id: cache-swiftformat
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/swiftformat
          key: ${{ runner.os }}-swiftformat-0.54.0
          restore-keys: |
            ${{ runner.os }}-swiftformat-

      - name: Install SwiftFormat
        if: steps.cache-swiftformat.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch 0.54.0 https://github.com/nicklockwood/SwiftFormat.git
          cd SwiftFormat
          swift build -c release --disable-sandbox
          sudo cp .build/release/swiftformat /usr/local/bin/

      - name: Run SwiftFormat
        run: swiftformat --swiftversion 6.2 . --lint
        
#      - name: Run SwiftLint
#        run: swiftlint --strict

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Swift 6.2
        run: |
          # Remove any existing Swift installation
          sudo rm -rf /usr/bin/swift /usr/bin/swiftc

          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y binutils git gnupg2 libc6-dev libcurl4-openssl-dev libedit2 libgcc-9-dev libpython3.8 libsqlite3-0 libstdc++-9-dev libxml2-dev libz3-dev pkg-config tzdata unzip zlib1g-dev curl

          # Download and install Swift 6.2
          wget https://download.swift.org/swift-6.2-release/ubuntu2204/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-6.2-RELEASE-ubuntu22.04.tar.gz
          sudo mv swift-6.2-RELEASE-ubuntu22.04 /usr/share/swift

          # Create symlinks for system-wide access
          sudo ln -sf /usr/share/swift/usr/bin/swift /usr/bin/swift
          sudo ln -sf /usr/share/swift/usr/bin/swiftc /usr/bin/swiftc
          sudo ln -sf /usr/share/swift/usr/bin/swift-build /usr/bin/swift-build
          sudo ln -sf /usr/share/swift/usr/bin/swift-package /usr/bin/swift-package
          sudo ln -sf /usr/share/swift/usr/bin/swift-test /usr/bin/swift-test

          # Add to PATH for this step and future steps
          echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH
        
      - name: Verify Swift 6.2 installation
        run: |
          swift --version
          which swift
          swift --version | grep -q "6.2" || (echo "Error: Swift 6.2 not properly installed" && exit 1)
          
      - name: Cache Swift packages
        id: cache-swift
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-
            
      - name: Build Debug
        run: swift build -v
        
      - name: Build Release
        run: swift build -c release -v

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Swift 6.2
        run: |
          # Remove any existing Swift installation
          sudo rm -rf /usr/bin/swift /usr/bin/swiftc

          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y binutils git gnupg2 libc6-dev libcurl4-openssl-dev libedit2 libgcc-9-dev libpython3.8 libsqlite3-0 libstdc++-9-dev libxml2-dev libz3-dev pkg-config tzdata unzip zlib1g-dev curl

          # Download and install Swift 6.2
          wget https://download.swift.org/swift-6.2-release/ubuntu2204/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-6.2-RELEASE-ubuntu22.04.tar.gz
          sudo mv swift-6.2-RELEASE-ubuntu22.04 /usr/share/swift

          # Create symlinks for system-wide access
          sudo ln -sf /usr/share/swift/usr/bin/swift /usr/bin/swift
          sudo ln -sf /usr/share/swift/usr/bin/swiftc /usr/bin/swiftc
          sudo ln -sf /usr/share/swift/usr/bin/swift-build /usr/bin/swift-build
          sudo ln -sf /usr/share/swift/usr/bin/swift-package /usr/bin/swift-package
          sudo ln -sf /usr/share/swift/usr/bin/swift-test /usr/bin/swift-test

          # Add to PATH for this step and future steps
          echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH

      - name: Verify Swift 6.2 installation
        run: |
          swift --version
          which swift
          swift --version | grep -q "6.2" || (echo "Error: Swift 6.2 not properly installed" && exit 1)

      - name: Cache Swift packages
        id: cache-swift
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Run tests
        run: swift test

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Swift 6.2
        run: |
          # Remove any existing Swift installation
          sudo rm -rf /usr/bin/swift /usr/bin/swiftc

          # Install dependencies
          sudo apt-get update
          sudo apt-get install -y binutils git gnupg2 libc6-dev libcurl4-openssl-dev libedit2 libgcc-9-dev libpython3.8 libsqlite3-0 libstdc++-9-dev libxml2-dev libz3-dev pkg-config tzdata unzip zlib1g-dev curl

          # Download and install Swift 6.2
          wget https://download.swift.org/swift-6.2-release/ubuntu2204/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-6.2-RELEASE-ubuntu22.04.tar.gz
          sudo mv swift-6.2-RELEASE-ubuntu22.04 /usr/share/swift

          # Create symlinks for system-wide access
          sudo ln -sf /usr/share/swift/usr/bin/swift /usr/bin/swift
          sudo ln -sf /usr/share/swift/usr/bin/swiftc /usr/bin/swiftc
          sudo ln -sf /usr/share/swift/usr/bin/swift-build /usr/bin/swift-build
          sudo ln -sf /usr/share/swift/usr/bin/swift-package /usr/bin/swift-package
          sudo ln -sf /usr/share/swift/usr/bin/swift-test /usr/bin/swift-test

          # Add to PATH for this step and future steps
          echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH
        
      - name: Verify Swift 6.2 installation
        run: |
          swift --version
          which swift
          swift --version | grep -q "6.2" || (echo "Error: Swift 6.2 not properly installed" && exit 1)
          
      - name: Cache Swift packages
        id: cache-swift
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-
            
      - name: Run KeyStore Benchmarks
        run: swift test --configuration release --filter KeyStoreBenchmarkTests | tee keystore-benchmark.log
        
      - name: Run KASService Benchmarks
        run: swift test --configuration release --filter KASServiceBenchmarkTests | tee kasservice-benchmark.log
        
      - name: Run NanoTDF Benchmarks
        run: swift test --configuration release --filter NanoTDFBenchmarkTests | tee nanotdf-benchmark.log
        
      - name: Upload benchmark logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            *-benchmark.log
          retention-days: 7
