name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DERIVED_DATA_PATH: ".build"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache SwiftFormat
        id: cache-swiftformat
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/swiftformat
          key: ${{ runner.os }}-swiftformat-0.54.0
          restore-keys: |
            ${{ runner.os }}-swiftformat-

      - name: Install SwiftFormat
        if: steps.cache-swiftformat.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch 0.54.0 https://github.com/nicklockwood/SwiftFormat.git
          cd SwiftFormat
          swift build -c release --disable-sandbox
          sudo cp .build/release/swiftformat /usr/local/bin/

      - name: Run SwiftFormat
        run: swiftformat --swiftversion 6.2 . --lint
        
#      - name: Run SwiftLint
#        run: swiftlint --strict

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache Swift packages
        id: cache-swift
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-
            
      - name: Build Debug
        run: swift build -v
        
      - name: Build Release
        run: swift build -c release -v

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.2

      - name: Print Swift version
        run: swift --version

      - name: Cache Swift packages
        id: cache-swift
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Run tests
        run: swift test

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: 6.2
        
      - name: Print Swift version
        run: swift --version
          
      - name: Cache Swift packages
        id: cache-swift
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-
            
      - name: Run KeyStore Benchmarks
        run: swift test --configuration release --filter KeyStoreBenchmarkTests | tee keystore-benchmark.log
        
      - name: Run KASService Benchmarks
        run: swift test --configuration release --filter KASServiceBenchmarkTests | tee kasservice-benchmark.log
        
      - name: Run NanoTDF Benchmarks
        run: swift test --configuration release --filter NanoTDFBenchmarkTests | tee nanotdf-benchmark.log
        
      - name: Upload benchmark logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            *-benchmark.log
          retention-days: 7
